quotes = {
    "The best way to predict the future is to create it.": 'Peter Drucker',
    "Time is what we want most, but what we use worst.": 'William Penn',
    "Yesterday is history, tomorrow is a mystery, today is a gift, which is why we call it the present.": 'Bil Keane',
    "Time flies over us, but leaves its shadow behind.": 'Nathaniel Hawthorne',
    "The two most powerful warriors are patience and time.": 'Leo Tolstoy',
    "Time is a created thing. To say 'I don't have time,' is like saying, 'I don't want to.'": 'Lao Tzu',
    "put things in order before they exist": 'Lao Tzu',
    "let your workings remain a mystery, just show people the results": 'Lao Tzu',
    "Time you enjoy wasting is not wasted time.": 'Marthe Troly-Curtin',
    "In the end, it's not the years in your life that count, it's the life in your years.": 'Abraham Lincoln',
    "The past is a ghost, the future a dream, and all we ever have is now.": 'Bill Cosby',
    "The key to immortality is first living a life worth remembering.": 'Bruce Lee',
    "Time is the wisest counselor of all.": 'Pericles',
    "To everything there is a season, and a time to every purpose under heaven.": 'Ecclesiastes 3:1',
    "Time is the school in which we learn, time is the fire in which we burn.": 'Delmore Schwartz',
    "Time is the most valuable thing a man can spend.": 'Theophrastus',
    "The only reason for time is so that everything doesn't happen at once.": 'Albert Einstein',
    "Time is what keeps everything from happening at once.": 'Ray Cummings',
    "Time waits for no one.": 'Folklore',
    "Time is the longest distance between two places.": 'Tennessee Williams',
    "Time is a great healer, but a poor beautician.": 'Lucille S. Harper',
    "The future is uncertain, but that can be a good thing.": 'Jennifer Niven',
    "The trouble with our times is that the future is not what it used to be.": 'Paul Valéry',
    "Lost time is never found again.": 'Benjamin Franklin',
    "The future depends on what you do today.": 'Mahatma Gandhi',
    "Time is the most valuable thing that we can spend.": 'Diogenes Laërtius',
    "The best thing about the future is that it comes one day at a time.": 'Abraham Lincoln',
    "Time brings all things to pass.": 'Aeschylus',
    "Time is a created thing. To say 'I don't have time,' is to say, 'I don't want to.'": 'Lao Tzu',
    "Time changes everything except something within us which is always surprised by change.": 'Thomas Hardy',
    "Time, the devourer of all things.": 'Ovid',
    "Time is the most precious element of human existence. The successful person knows how to put energy into time and how to draw success from time.": 'Denis Waitley',
    "We must use time creatively, in the knowledge that the time is always ripe to do right.": 'Martin Luther King Jr.',
    "Time is a brisk wind, for each hour it brings something new... but who can understand and measure its sharp breath, its mystery and its design?": 'Paracelsus',
    "Prediction is very difficult, especially about the future.": 'Niels Bohr',
    "The best way to predict your future is to create it.": 'Abraham Lincoln',
    "Those who have knowledge, don't predict. Those who predict, don't have knowledge.": 'Lao Tzu',
    "Your future is whatever you make it, so make it a good one.": 'Doc Brown, "Back to the Future"',
    "The future belongs to those who prepare for it today.": 'Malcolm X',
    "An economist is an expert who will know tomorrow why the things he predicted yesterday didn't happen today.": 'Laurence J. Peter',
    "Forecasting is the art of saying what will happen, and then explaining why it didn't.": 'Anonymous',
    "The only function of economic forecasting is to make astrology look respectable.": 'John Kenneth Galbraith',
    "The future is always beginning now.": 'Mark Strand',
    "He who lives by the crystal ball will eat shattered glass.": 'Ray Dalio',
    "It's tough to make predictions, especially about the future.": 'Yogi Berra',
    "Prediction is not a matter of knowing what will happen, but of knowing what to do when it happens.": 'Epictetus',
    "The future isn't just a place you'll go, it's a place you will invent.": 'Nancy Duarte',
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.": 'Buddha',
    "The real problem is not whether machines think but whether men do.": 'B.F. Skinner',
    "Artificial intelligence is no match for natural stupidity.": 'Anonymous',
    "The future belongs to those who believe in the beauty of their dreams.": 'Eleanor Roosevelt',
    "The measure of intelligence is the ability to change.": 'Albert Einstein',
    "The best way to predict the future is to invent it.": 'Alan Kay',
    "Intelligence is the ability to adapt to change.": 'Stephen Hawking',
    "Computers are incredibly fast, accurate, and stupid; humans are incredibly slow, inaccurate, and brilliant; together they are powerful beyond imagination.": 'Albert Einstein',
    "AI is a tool. The choice about how it gets deployed is ours.": 'Oren Etzioni',
    "The science of today is the technology of tomorrow.": 'Edward Teller',
    "Man is still the most extraordinary computer of all.": 'John F. Kennedy',
    "We are stuck with technology when what we really want is just stuff that works.": 'Douglas Adams',
    "Artificial intelligence will reach human levels by around 2029. Follow that out further to, say, 2045, we will have multiplied the intelligence, the human biological machine intelligence of our civilization a billion-fold.": 'Ray Kurzweil',
    "What is now proved was once only imagined.": 'William Blake',
}
